### ISSUE TITLE
How to get the consensus TE sequences for non-model species?

### ISSUE THREAD

**Issue by huawen-poppy** [jmzvillarreal/kallisto_TE_scRNAseq#1]
Hello, thank you for your inspiring work. I wonder how can we get the consensus TE sequences for the non-model species?

**Comment by jmzvillarreal** [comment]
Hi,
Thanks for your interest in our work.
You can access those sequences in repbase db:
https://www.girinst.org/repbase/update/browse.php
Sadly, it's subscribed users only.
Best,
Jaime.

**Comment by huawen-poppy** [comment]
Hmm, I see. Thanks for your reply!
